markdown: kramdown
permalink: /:year/:month/:day/:title.html

# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# weibo:    ID
github: kbBlog

author: Wen Fu Bin

baseurl: "" #根目录

title: "空白's Blog"

sass:
  style: compressed

highlighter: rouge